name: 'Terraform'

on:
  push:
    branches: [ '**' ]

jobs:
  terraform:
    uses: silinternational/workflows/.github/workflows/terraform.yml@main
    with:
      test-dir: test
      # validate with the earliest version allowed by required_version in versions.tf
      terraform-version: '~> 1.0'
